version: '3'
services:
  splunk:
    container_name: splunk
    build:
      context: .
      dockerfile: sample/splunk/Dockerfile
    volumes:
      - "./sample/splunk/default.yml:/tmp/defaults/default.yml"
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes --seed-passwd changeme
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_PASSWORD: changemeplease!
      SPLUNK_HEC_TOKEN: 00112233-4455-6677-8899-AABBCCDDEEFF

  sampleconsoleapp:
    container_name: sample
    depends_on:
      - "splunk"
    build:
      context: .
      dockerfile: sample/Sample/Dockerfile
