# If this file is renamed, the incrementing run attempt number will be reset.

name: CI

on:
  push:
    tags:
      - '*'

env:
  CI_BUILD_NUMBER: ${{ github.run_number }}
  CI_TARGET_BRANCH: ${{ github.head_ref || github.ref_name }}
  CI_COMMIT_TAG: ${{ github.ref_name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build and Publish
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        shell: pwsh
        run: |
          ./Build.ps1
